import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workflow = await readFile(resolve(root, ".github/workflows/release.yml"), "utf8");
const storeWorkflow = await readFile(resolve(root, ".github/workflows/store-msix.yml"), "utf8");
const msixBuildScript = await readFile(resolve(root, "scripts/build-msix.ps1"), "utf8");

assert.match(workflow, /concurrency:\s+group:\s+release-\$\{\{\s*inputs\.tag\s*\}\}/);
assert.match(workflow, /allow_unsigned_windows:/);
assert.match(workflow, /type:\s+boolean/);
assert.match(workflow, /inputs\.allow_unsigned_windows/);
assert.equal((workflow.match(/bash scripts\/check-version\.sh[^\n]*/g) ?? []).length, 2);
assert.equal((workflow.match(/actions\/upload-artifact@v4/g) ?? []).length, 2);
assert.equal((workflow.match(/softprops\/action-gh-release@v2/g) ?? []).length, 1);
assert.match(workflow, /actions\/download-artifact@v4/);
assert.match(workflow, /needs:\s*\[build-macos, build-windows\]/);
assert.match(workflow, /id:\s+release_metadata/);
assert.match(workflow, /name:\s+EiSen \$\{\{\s*steps\.release_metadata\.outputs\.version\s*\}\}/);
assert.match(workflow, /## What's Changed in EiSen/);
assert.match(workflow, /### ✨ Highlights & Improvements/);
assert.match(workflow, /### 🔐 Checksums/);
assert.match(workflow, /shasum -a 256/);
assert.match(workflow, /Get-FileHash -Algorithm SHA256/);
assert.match(workflow, /Get-AuthenticodeSignature/);
assert.match(workflow, /WINDOWS_CERTIFICATE_BASE64/);
assert.match(workflow, /Set-Content -LiteralPath .* -Encoding ascii -NoNewline/);
assert.match(workflow, /--no-sign/);
assert.match(workflow, /NotSigned/);
assert.match(workflow, /unsigned Windows/i);
assert.match(workflow, /Windows installer status:/);
assert.match(workflow, /SmartScreen/);
assert.match(workflow, /timestampUrl/);
assert.match(workflow, /codesign --verify --deep --strict/);
assert.match(workflow, /xcrun stapler validate/);

assert.match(storeWorkflow, /^name:\s*Store MSIX\s*$/m);
assert.match(storeWorkflow, /workflow_dispatch:/);
assert.match(storeWorkflow, /ref:\s*[\s\S]*default:\s*main/);
assert.match(storeWorkflow, /version:\s*[\s\S]*default:\s*0\.2\.5\.0/);
assert.match(storeWorkflow, /runs-on:\s*windows-latest/);
assert.match(storeWorkflow, /microsoft\/setup-WinAppCli@v0\.1/);
assert.match(storeWorkflow, /scripts\/check-version\.sh/);
assert.match(storeWorkflow, /build-msix\.ps1\s+-Mode\s+test/);
assert.match(storeWorkflow, /build-msix\.ps1\s+-Mode\s+store/);
assert.match(storeWorkflow, /Add-AppxPackage/);
assert.match(storeWorkflow, /Get-StartApps/);
assert.match(storeWorkflow, /shell:AppsFolder/);
assert.match(storeWorkflow, /Remove-AppxPackage/);
assert.match(storeWorkflow, /eisen-store-msix-\$\{\{\s*inputs\.version\s*\}\}/);
assert.match(storeWorkflow, /actions\/upload-artifact@v4/);

assert.match(msixBuildScript, /ValidateSet\('store',\s*'test'\)/);
assert.match(msixBuildScript, /--no-bundle/);
assert.match(msixBuildScript, /manifest update-assets/);
assert.match(msixBuildScript, /winapp pack/);
assert.match(msixBuildScript, /--generate-cert/);
assert.match(msixBuildScript, /--install-cert/);
assert.match(msixBuildScript, /Get-FileHash/);
assert.match(msixBuildScript, /2>&1/);
assert.match(msixBuildScript, /Write-Host/);
assert.match(msixBuildScript, /finally/);

console.log("release workflow contract: ok");
